[platformio]
default_envs = esp32-s3
src_dir = esp32_rangoli_bot

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    madhephaestus/ESP32Servo @ ^1.1.0
    links2004/WebSockets @ ^2.4.1

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
